### ISSUE TITLE
Question: How right way to use python-mediator with dependency-injector?

### ISSUE THREAD

**Issue by torugok** [dlski/python-mediator#3]
Hello, I'm testing your nice lib in project of my company, and, I have a question about the right way to use dependency injector with python-mediator, I'm currently implementing with below way:

app/shared/application/event_handler.py:
```python
from abc import ABC, abstractmethod
from typing import Any


class EventHandler(ABC):
    @abstractmethod
    async def handle(self, event: Any):
        pass
```

And an example of event handler implementation:

![Screenshot from 2021-10-30 14-24-11](https://user-images.githubusercontent.com/1656859/139542978-f04e2eda-c764-42bb-a96d-af5670b9820d.png)

And after this, I'm use a concrete impl for registry of class handlers:

![Screenshot from 2021-10-30 14-25-14](https://user-images.githubusercontent.com/1656859/139543022-e00ca4c6-6acb-4d3f-adc7-afc5411a72ab.png)

My main question is to avoid a "Handler" class registering as static class, because I imagine that when this event is called twice at the same time, I might have inconsistencies (sharing resources between two executions of handlers, like an Sqlalchemy Unit Of Work), is there any way to mitigate this?

PS: I'm very beggining in world of event driven, async await, ddd, CQRS

**Comment by dlski** [comment]
Hello!
I don't have full context here and I didn't work with `dependency-injector` library before, but I think command/query bus - `LocalRequestBus` may help you.
As I see you try to find smart way to pass command handler to perform some action when particular event is received. I think you can generalize any command/query invoke here and you can pass only "request bus" - command object is enough to find it's handler (`LocalRequestBus` is unicast equivalent to broadcast `LocalEventBus`).

As a workaround, if you want to pass any combinations of arguments, you can define your handler initializer to have variable keyword args like  `def __init__(self, **kwargs):` and later in dependency injection code: `handler(request_bus=..., my_extra_arg1=..., my_extra_arg2=..., ...)`. When you want to execute some commands, you can extend `def __init__(self, request_bus: RequestExecutor, **kwargs):` and later in handler `result = await self.request_bus.execute(new MyCommand(...))`.

Hope it helps.

PS: Some tips&tricks and more detailed use will be provided in docs - due to limited time resources, it will take a while to release.
